### ISSUE TITLE
Procedures for Minex-III certification for our fingerprint device

### ISSUE THREAD

**Issue by dossbics** [usnistgov/minex#4]
What will be the software testing for Minex-III certification. Please any one could clarify this process.

**Comment by gfiumara** [comment]
Thanks for your interest in MINEX III. You should prepare a library compliant with the [MINEX III API](https://www.nist.gov/document/minexiiitestplanpdf) and then run it against our [validation code](https://github.com/usnistgov/minex/tree/master/minexiii/validation). The validation code will generate a file that you send to minex@nist.gov for testing. Once complete, we upload the results to our website. Before posting your results, we must receive a hard copy of the signed [agreement form](https://www.nist.gov/sites/default/files/documents/2018/02/15/minexiii_application.pdf).

You can find more information about participating on [our website](https://www.nist.gov/itl/iad/image-group/participation-minex-iii). If you have more questions, please e-mail us at minex@nist.gov. I will now close this issue request, because this GitHub forum is more appropriate for commenting on issues with the MINEX source code.
